-- DROP TABLE TO CLEAR ALL TABLE OF DATA
DROP TABLE IF EXISTS CART, FULFILLMENT, ORDERED, ORDERS, PRODUCTS, EMPLOYEES, USERS;

-- USER TABLE 
CREATE TABLE USERS (
    USERID DOUBLE(6,0) ZEROFILL NOT NULL AUTO_INCREMENT,
    EMAIL CHAR(20) NOT NULL,
    PASSWORD CHAR(20) NOT NULL,
    USERNAME CHAR(20) NOT NULL, 
    BADDRESS CHAR(20) NOT NULL, -- BILLING ADDRESS
    BCITY CHAR(20) NOT NULL,   
    BSTATE CHAR(2) NOT NULL,
    BZIP CHAR(6),  -- BILLING ADDRESS ENDS, CHECK TO MAKE SURE ZIP IS FILLED
    CARDNUM CHAR(16),-- CHECK TO MAKE SURE CARD IS FULL NUMBER  

    PRIMARY KEY (USERID)
);

-- PRODUCTS TABLE 
CREATE TABLE PRODUCTS(
    PRODID DOUBLE(6,0) ZEROFILL NOT NULL AUTO_INCREMENT, -- PRIME
    PRODNAME CHAR(20) NOT NULL,
    PRICE DOUBLE(11,2) UNSIGNED NOT NULL,  -- 11 DIGITS TOTAL WITH 2 DECIMALS  XXX,XXX,XXX.XX
    CATAGORY CHAR(20) NOT NULL,
    DESCRIPTION BLOB, 
    QUANTITY INT NOT NULL, 
    STATUS BOOL NOT NULL, -- 1 FOR INSTOCK 0 FOR OUT OF STOCK

    PRIMARY KEY (PRODID)
);

-- USER ORDERS 
CREATE TABLE ORDERS(
    ORDERID DOUBLE(6,0) ZEROFILL NOT NULL AUTO_INCREMENT, -- PRIME
    USERID DOUBLE(6,0) NOT NULL, -- FOREIGN
    SADDRESS CHAR(20) NOT NULL, -- SHIPPING ADDRESS
    SCITY CHAR(20) NOT NULL,
    SSTATE CHAR(2) NOT NULL,
    SZIP CHAR(6),  -- SHIPPING ADDRESS ENDS, CHECK TO MAKE SURE ZIP IS FILLED
    TOTAL DOUBLE(11,2) UNSIGNED NOT NULL,  -- 11 DIGITS TOTAL WITH 2 DECIMALS XXX,XXX,XXX.XX
    ORDERSTATUS CHAR(20) NOT NULL, -- CHAR FOR THINGS LIKE "PENDING PAYMENT" "OUT FOR SHIPPING" ECT. 
    TRACKINGID DOUBLE(8,0) ZEROFILL NOT NULL,

    PRIMARY KEY (ORDERID),
    FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

-- SHOPPING CART 
CREATE TABLE CART(
    USERID DOUBLE(6,0) ZEROFILL NOT NULL, -- FOREIGN PRIME
    PRODID DOUBLE(6,0) ZEROFILL NOT NULL, -- FOREIGN PRIME
    QUANTITY INT NOT NULL, 

    PRIMARY KEY (USERID, PRODID),
    FOREIGN KEY (USERID) REFERENCES USERS (USERID), 
    FOREIGN KEY (PRODID) REFERENCES PRODUCTS (PRODID) 
);

-- ORDERED PRODUCTS TABLE 
CREATE TABLE ORDERED (
    ORDERID DOUBLE(6,0) ZEROFILL NOT NULL, -- FOREIGN PRIME
    PRODID DOUBLE(6,0) ZEROFILL NOT NULL,  -- FOREIGN PRIME
    QUANTITY INT NOT NULL,

    PRIMARY KEY (ORDERID, PRODID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID),
    FOREIGN KEY (PRODID) REFERENCES PRODUCTS (PRODID)
);

-- EMPLOYEES FOR EMPLOYEES
CREATE TABLE EMPLOYEES(
    EMPID DOUBLE(6,0) ZEROFILL NOT NULL AUTO_INCREMENT, -- PRIME
    ENAME CHAR(20) NOT NULL,
    ISOWNER BOOL NOT NULL,  -- 1 IF TRUE, 0 IF FALSE

    PRIMARY KEY (EMPID)
);

-- FULFILLMENT OF ORDER EMPLOYEE SIDE
CREATE TABLE FULFILLMENT(
    ORDERID DOUBLE(6,0) ZEROFILL NOT NULL, -- FOREIGN PRIME
    EMPID DOUBLE(6,0) ZEROFILL NOT NULL, -- FOREIGN PRIME
    COMMENTS BLOB, -- COMMENT FROM EMPLOYEE ABOUT ORDER

    PRIMARY KEY (ORDERID, EMPID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID),
    FOREIGN KEY (EMPID) REFERENCES EMPLOYEES (EMPID)
);