INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailA@email.com', 'password', 'Person 1', 'Address A', 'City A', 'ST', '123456', '123456789ABCDEFG');
INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailB@email.com', 'password', 'Person 2', 'Address B', 'City A', 'ST', '123456', '0123456789ABCDEF');

INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product A', 1.00, 'A, 'Address B', 10, 1);