INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailA@email.com', 'password', 'Person 1', 'Address A', 'City A', 'ST', '123456', '123456789ABCDEFG');
INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailB@email.com', 'password', 'Person 2', 'Address B', 'City A', 'ST', '123456', '0123456789ABCDEF');
INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailC@email.com', 'password', 'Person 3', 'Address A', 'City A', 'ST', '123456', '123456789ABCDEFG');
INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailD@email.com', 'password', 'Person 4', 'Address B', 'City A', 'ST', '123456', '0123456789ABCDEF');
INSERT INTO USERS
    (EMAIL, PASSWORD, USERNAME, BADDRESS, BCITY, BSTATE, BZIP, CARDNUM)
    VALUES ('emailE@email.com', 'password', 'You', 'Address A', 'City A', 'ST', '123456', '123456789ABCDEFG');

INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product A', 1.00, 'A', 'Desc A', 10, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product B', 1.99, 'B', 'Desc B', 100, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product C', 13.99, 'C', 'Desc Sea', 8751, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 4', 124.00, 'A', 'Desc asdadadadaA', 245, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 5', 14.99, 'B', 'Desc Bwqeqeqrqwrwrq', 45343, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 6', 1.49, 'C', 'Desc Ssadasdasdwqdwqea', 4534, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 7', 1.00, 'A', 'Desc A', 10, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 8', 1.99, 'B', 'Desc B', 100, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 9', 13.99, 'C', 'Desc Sea', 0, 0);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 10', 124.00, 'A', 'Desc asdadadadaA', 245, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 11', 14.99, 'B', 'Desc Bwqeqeqrqwrwrq', 45343, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 12', 1.49, 'C', 'Desc Ssadasdasdwqdwqea', 4534, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 13', 124.00, 'A', 'Desc asdadadadaA', 245, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 14', 14.99, 'B', 'Desc Bwqeqeqrqwrwrq', 45343, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 15', 1.49, 'C', 'Desc Ssadasdasdwqdwqea', 4534, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 16', 1.00, 'A', 'Desc A', 10, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 17', 1.99, 'B', 'Desc B', 100, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 18', 13.99, 'C', 'Desc Sea', 0, 0);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Product 19', 124.00, 'A', 'Desc asdadadadaA', 245, 1);
INSERT INTO PRODUCTS
    (PRODNAME, PRICE, CATAGORY, DESCRIPTION, QUANTITY, STATUS)
    VALUES ('Apple', 1004.99, 'B', 'Desc Fruit', 4557343, 1);

INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (1, 'Address A', 'City A', 'ST', '123456', 10.00, 'PROCESSING', 1);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (1, 'Address A', 'City A', 'ST', '123456', 5.00, 'SHIPPED', 3);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (2, 'Address A', 'City A', 'ST', '123456', 20.00, 'PROCESSING', 2);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (3, 'Address A', 'City A', 'ST', '123456', 10.00, 'PROCESSING', 1);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (4, 'Address A', 'City A', 'ST', '123456', 20.00, 'PROCESSING', 2);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (5, 'Address A', 'City A', 'ST', '123456', 20.00, 'PROCESSING', 2);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (5, 'Address A', 'City A', 'ST', '123456', 5.00, 'SHIPPED', 3);
INSERT INTO ORDERS
    (USERID, SADDRESS, SCITY, SSTATE, SZIP, TOTAL, ORDERSTATUS, TRACKINGID)
    VALUES (5, 'Address A', 'City A', 'ST', '123456', 20.00, 'PROCESSING', 2);

INSERT INTO CART
    (USERID, PRODID, QUANTITY)
    VALUES (1, 1, 5);

INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (1, 1, 2);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (2, 1, 20);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (3, 3, 2);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (4, 2, 20);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (5, 1, 2);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (6, 2, 20);
INSERT INTO ORDERED
    (ORDERID, PRODID, QUANTITY)
    VALUES (7, 2, 20);

INSERT INTO EMPLOYEES
    (ENAME, ISOWNER)
    VALUES ('EMPLOYEE A', 1);
INSERT INTO EMPLOYEES
    (ENAME, ISOWNER)
    VALUES ('EMPLOYEE B', 1);

INSERT INTO FULFILLMENT
    (ORDERID, EMPID, COMMENTS)
    VALUES (2,1, 'Hello World');
INSERT INTO FULFILLMENT
    (ORDERID, EMPID, COMMENTS)
    VALUES (7,1, 'I like the socks');